// <auto-generated> 由解包资源扫描生成（2026-09-30 v1.2.0），勿手改。
//
// 只覆盖**白卡**（GeneralPlant.category.White，188 张），一张卡可属多个类别。
// 判据：角色 *ComponentSet.tres 组件 + TowerDefenseCharacterConfig 的
//       physiqueTypeFlags / plantGridType / elementFlags / hitpoints + 名称关键词（不区分大小写）。
// ⚠️ 构建期烘焙；游戏更新新增的卡不在表里 ⇒ Entry 会用同样的「标志+关键词」再兜一轮，
//    仍无归属的自动进「其他」（见 ClassifyRuntime）。
using System.Collections.Generic;

internal static class WhiteCardCategoriesTable
{
	internal static readonly Dictionary<string, string[]> Map = new Dictionary<string, string[]>
	{
		{ "阳光", new[] { "PlantSunflowerPea", "PlantSunBomb", "PlantSunMine", "PlantSunShroom", "PlantSunBean", "PlantScaredySunShroom", "PlantJalaSunShroom", "PlantIceSunShroom", "PlantSunPad", "PlantPumpkinSun", "PlantSunPot", "PlantCatFlower", "PlantSunpult", "PlantSunPeashooter", "PlantMariGoldMagnet", "PlantNutFlower", "PlantSunFlowerZ", "PlantSunFlagbean", "PlantSunFlowerQX", "PlantSunTransfer", "PlantSunShroomCharge", "PlantEnergyBean", "PlantSunFlowerMagic", "PlantPotSale", "PlantHypnoShroomSun" } },
		{ "豌豆射手", new[] { "PlantSunflowerPea", "PlantReCactus", "PlantPuffPot", "PlantPeaPot", "PlantCatPot", "PlantScaredySunShroom", "PlantIcenut", "PlantWinterMelonShroom", "PlantPeaLilyPad", "PlantFireSnowPea", "PlantGloompult", "PlantPeaCat", "PlantSeaNut", "PlantMelonpultSpike", "PlantPeaWell", "PlantMagnetShroomIce", "PlantCornpultM", "PlantPumpkinSun", "PlantKabbageTail", "PlantSeaStar", "PlantCatFlower", "PlantCatPumpkin", "PlantSunPeashooter", "PlantThreePeaterG", "PlantIceCactus", "PlantPiratePeater", "PlantPumpkinPea", "PlantCherryPea", "PlantPeashooterZ", "PlantThreePeaterZ", "PlantCactusQX", "PlantStarRobot", "PlantCornpultGene", "PlantCatTailTP", "PlantPeaShooterMagic", "PlantPuffShroomElf", "PlantThreeHybirdPeater", "PlantSnowPeaCat", "PlantGatlingCabbage", "PlantStarPeater", "PlantSplitPeaCat", "PlantMagnetshroomS", "PlantSealeaf" } },
		{ "坚果防御", new[] { "PlantFirenut", "PlantMagnetnut", "PlantIcenut", "PlantSeaNut", "PlantJalaNut", "PlantPumpkinFire", "PlantWallnutABC_A", "PlantPumpkinSun", "PlantCatPumpkin", "PlantMelonnut", "PlantNutleaf", "PlantPumpkinCannon", "PlantStarleaf", "PlantWallnutSquash", "PlantWallnutHole", "PlantImitaterW", "PlantPumpkinPea", "PlantNutFlower", "PlantNutpult", "PlantWallnutZ", "PlantWallnutQX", "PlantPumpkinRobot", "PlantMagnetPumpkin", "PlantGuardNut", "PlantPrimalNut", "PlantGarlicTallnut", "PlantTallnutUmbrella", "PlantPumpkinBig", "PlantHurtTallnut", "PlantWallnutSale", "PlantPumpkinPult", "PlantPumpkinNut" } },
		{ "火焰", new[] { "PlantFirenut", "PlantJalaSunShroom", "PlantFireSnowPea", "PlantSnowwood", "PlantJalaCherryBomb", "PlantSunPad", "PlantPumpkinFire", "PlantSunPeashooter", "PlantJalaTorch", "PlantJalapult", "PlantDoomShroomF", "PlantRichwood", "PlantPowShroom", "PlantUmbrellaTorch", "PlantFeverStar", "PlantFeverBlover", "PlantTorchwoodZ", "PlantTorchwoodStar", "PlantJalaJoker", "PlantJalapenopepe", "PlantGarlicJalapeno", "PlantJalaGhost", "PlantPotatoMineR", "PlantGarlicWood" } },
		{ "爆炸一次性", new[] { "PlantSunBomb", "PlantSunMine", "PlantGraveMine", "PlantMagnetMine", "PlantJalaSunShroom", "PlantJalaNut", "PlantJalaCherryBomb", "PlantIceSquash", "PlantPotatoCobCannon", "PlantJalaTorch", "PlantJalapult", "PlantSquashKing", "PlantWallnutSquash", "PlantGloomSquash", "PlantCherryPea", "PlantBungiSquash", "PlantEMPCherry", "PlantDiceBomb", "PlantPotatoMineQX", "PlantWildMine", "PlantPotatoStar", "PlantJalaJoker", "PlantGarlicBomb", "PlantJalapenopepe", "PlantGarlicJalapeno", "PlantJalaGhost", "PlantGravebomber", "PlantMagnetBomb", "PlantCherryMine", "PlantIceBomb", "PlantPotatoSquash", "PlantCherryBean", "PlantPotatoMineR", "PlantKelpMine" } },
		{ "蘑菇", new[] { "PlantSunShroom", "PlantScaredySunShroom", "PlantSnowShroom", "PlantWinterMelonShroom", "PlantGargantuarShroom", "PlantJalaSunShroom", "PlantIceSunShroom", "PlantTabooDoomShroom", "PlantIceSeaShroom", "PlantMagnetShroomIce", "PlantSpringFumeShroom", "PlantDoomShroomF", "PlantPowShroom", "PlantSquidGloomShroom", "PlantStressShroom", "PlantLampShroom", "PlantSunShroomCharge", "PlantMagnetShroomDM", "PlantPuffShroomElf", "PlantHypnoShroomLight", "PlantFumeShroomC", "PlantFumeSeaShroom", "PlantHypnoShroomSun", "PlantMagnetshroomS" } },
		{ "吹风清障", new[] { "PlantCactusBlover", "PlantSnowBlover", "PlantFeverBlover", "PlantHypnoBlover", "PlantCoffeeBlover" } },
		{ "磁力", new[] { "PlantMagnetnut", "PlantMagnetMine", "PlantMagnetShroomIce", "PlantMariGoldMagnet", "PlantFeverBlover", "PlantMagnetShroomDM", "PlantMagnetPumpkin", "PlantMagnetBomb", "PlantMagnetshroomS" } },
		{ "花盆", new[] { "PlantPuffPot", "PlantPeaPot", "PlantCatPot", "PlantSunPot", "PlantPotSpike", "PlantPotGarlic", "PlantPotVampire", "PlantLilyPot", "PlantMedicPot", "PlantPotSale", "PlantHypnoPot" } },
		{ "猫尾", new[] { "PlantCatPot", "PlantPeaCat", "PlantKabbageTail", "PlantCatFlower", "PlantCatPumpkin", "PlantCatTailZ", "PlantCatTailTP", "PlantSnowPeaCat", "PlantGWC", "PlantSplitPeaCat", "PlantSWC", "PlantHWC" } },
		{ "地刺", new[] { "PlantCorntrop", "PlantMelonpultSpike", "PlantPotSpike", "PlantCaltropSnow", "PlantCaltropZ", "PlantStarCaltrop" } },
		{ "辅助道具", new[] { "PlantSunBean", "PlantMariGoldMagnet", "PlantTabooBean", "PlantPanGoldBean", "PlantCoffeebeanSale", "PlantUpgradebean", "PlantSunFlagbean", "PlantHypnoBean", "PlantSunTransfer", "PlantEnergyBean", "PlantMagicBean", "PlantMagicRoot", "PlantWallnutSale", "PlantPotSale", "PlantCherryBean", "PlantPresentBox" } },
		{ "大蒜", new[] { "PlantHypnoGarlic", "PlantGarlicChomper", "PlantPotGarlic", "PlantGarlicBird", "PlantGarlicBomb", "PlantGarlicJalapeno", "PlantGarlicTallnut", "PlantGarlicWood" } },
		{ "催眠", new[] { "PlantHypnoGarlic", "PlantHypnoBean", "PlantHypnoBlover", "PlantHypnoShroomLight", "PlantHypnoShroomSun", "PlantHypnoPot" } },
		{ "墓碑清理", new[] { "PlantGraveMine", "PlantGhostbuster", "PlantGravebomber" } },
		{ "冰冻", new[] { "PlantIcenut", "PlantSnowShroom", "PlantWinterMelonShroom", "PlantFireSnowPea", "PlantIceSunShroom", "PlantSnowwood", "PlantIceSeaShroom", "PlantMagnetShroomIce", "PlantSnowBlover", "PlantSeaStar", "PlantIceSquash", "PlantCaltropSnow", "PlantIceCactus", "PlantWinterMelonX", "PlantDiceBomb", "PlantSnowPeaCat", "PlantSnowCornpult", "PlantIceBomb", "PlantMagnetshroomS" } },
		{ "水草水生", new[] { "PlantPeaLilyPad", "PlantSeaNut", "PlantTanglekelpH", "PlantDoomTanglekelp", "PlantIceSeaShroom", "PlantPlanternTanglekelp", "PlantSeaStar", "PlantCatTailZ", "PlantCatTailTP", "PlantLilyPot", "PlantFumeSeaShroom", "PlantKelpMine", "PlantSealeaf" } },
		{ "投掷", new[] { "PlantGloompult", "PlantMelonpultSpike", "PlantCornpultM", "PlantCabbageCob", "PlantPotatoCobCannon", "PlantSunpult", "PlantPumpkinCannon", "PlantJalapult", "PlantPowShroom", "PlantNutpult", "PlantCornpultGene", "PlantMagnetShroomDM", "PlantSnowCornpult", "PlantThreeCornpult", "PlantCabbagepultInside", "PlantPumpkinPult" } },
		{ "可种水中", new[] { "PlantPeaCat", "PlantSunPad", "PlantPeaWell", "PlantKabbageTail", "PlantCatPumpkin", "PlantWallnutHole", "PlantSquidGloomShroom", "PlantDiceBomb", "PlantSnowPeaCat", "PlantGWC", "PlantSplitPeaCat", "PlantSWC", "PlantHWC" } },
		{ "灯光", new[] { "PlantPlanternSix", "PlantPlanternTanglekelp", "PlantHammerLight", "PlantPumpLantern", "PlantLampShroom", "PlantPlanternTime", "PlantEMPlantern", "PlantHypnoShroomLight", "PlantMedicPlantern" } },
		{ "大嘴花", new[] { "PlantChomperBlow", "PlantGarlicChomper", "PlantChomperPot", "PlantChomperZ" } },
		{ "咖啡", new[] { "PlantCoffeeleaf", "PlantCoffeebeanSale", "PlantCoffeeBlover" } },
		{ "模仿者", new[] { "PlantImitaterW" } },
		{ "僵尸系", new[] { "PlantBYWZ", "PlantPeashooterZ", "PlantSunFlowerZ", "PlantWallnutZ", "PlantChomperZ", "PlantThreePeaterZ", "PlantTorchwoodZ", "PlantCaltropZ", "PlantCatTailZ" } },
		{ "魔法", new[] { "PlantMagicBean", "PlantPeaShooterMagic", "PlantSunFlowerMagic", "PlantPuffShroomElf", "PlantHypnoShroomLight", "PlantPotVampire", "PlantMagicRoot" } },
	};

	/// <summary>类别显示顺序（「其他」由运行时按需追加，不在这里）。</summary>
	internal static readonly string[] Order = new[]
	{
		"阳光",
		"豌豆射手",
		"坚果防御",
		"火焰",
		"爆炸一次性",
		"蘑菇",
		"吹风清障",
		"磁力",
		"花盆",
		"猫尾",
		"地刺",
		"辅助道具",
		"大蒜",
		"催眠",
		"墓碑清理",
		"冰冻",
		"水草水生",
		"投掷",
		"可种水中",
		"灯光",
		"大嘴花",
		"咖啡",
		"模仿者",
		"僵尸系",
		"魔法"
	};
}
