# -*- coding: utf-8 -*-
"""由 `../data/whitecard_tags.json` 生成 `../runtime_src/WhiteCardCategoriesTable.cs`。

紧凑编码：每行 "植物键|标签1,标签2,..."，启动时解析成字典。
好处：生成与核对都容易，改动在 git diff 里一目了然。

用法：
    python tools/gen_whitecard_table.py
"""
import json
import pathlib

BASE = pathlib.Path(__file__).resolve().parent.parent      # Mod 根目录
J = BASE / "data" / "whitecard_tags.json"
OUT = BASE / "runtime_src" / "WhiteCardCategoriesTable.cs"


def main() -> int:
    if not J.is_file():
        print("找不到数据文件，请先跑 extract_whitecard_tags.py：", J)
        return 1
    d = json.loads(J.read_text(encoding="utf-8"))
    group_order = d["groupOrder"]
    groups = d["groups"]
    plants = d["plants"]
    tag_total = sum(len(v) for v in groups.values())

    L = []
    L.append("// <auto-generated> 由《白卡植物标签表.xlsx》生成，勿手改。")
    L.append("//")
    L.append("// 数据来源：表格「标签字典」的分组列 + 「白卡植物标签」的标签列。")
    L.append("//   5 大类 = " + " / ".join(group_order))
    L.append("//   （字典里的「备注/脚本特化」命中 0，表格说明已并入「其他」，故不设该大类）")
    L.append("// 覆盖表格全部 {} 株白卡植物、{} 个标签。".format(len(plants), tag_total))
    L.append("//")
    L.append("// ⚠️ 本表是「构建期烘焙」。游戏更新/Mod 新增的白卡不在表里 ⇒ Entry 会用")
    L.append("//    `WhiteCardAutoTagger`（配置字段 + 名称关键词 + 组件集）再兜一轮，")
    L.append("//    仍无归属的自动进「其他」，不会漏卡。")
    L.append("//")
    L.append("// 重新生成：python tools/extract_whitecard_tags.py && python tools/gen_whitecard_table.py")
    L.append("// 回环校验：python tools/verify_table_roundtrip.py")
    L.append("using System.Collections.Generic;")
    L.append("")
    L.append("internal static class WhiteCardCategoriesTable")
    L.append("{")
    L.append("\t/// <summary>5 大类的显示顺序（与表格「标签字典」的分组一致）。</summary>")
    L.append("\tinternal static readonly string[] GroupOrder = { "
             + ", ".join('"{}"'.format(g) for g in group_order) + " };")
    L.append("")
    L.append("\t/// <summary>大类 → 该大类下的标签（顺序即表格「标签字典」的行序）。</summary>")
    L.append("\tinternal static readonly Dictionary<string, string[]> Groups = new Dictionary<string, string[]>")
    L.append("\t{")
    for g in group_order:
        L.append('\t\t{{ "{}", new[] {{ {} }} }},'.format(
            g, ", ".join('"{}"'.format(t) for t in groups[g])))
    L.append("\t};")
    L.append("")
    L.append("\t/// <summary>植物键 → 标签，编码为 \"键|标签1,标签2\"。</summary>")
    L.append("\tinternal static readonly string[] PlantTagLines =")
    L.append("\t{")
    for k, v in plants.items():
        L.append('\t\t"{}|{}",'.format(k, ",".join(v["tags"])))
    L.append("\t};")
    L.append("}")
    L.append("")

    OUT.write_text("\n".join(L), encoding="utf-8", newline="\n")
    print("已生成:", OUT)
    print("  行数:", len(L), " 大小:", OUT.stat().st_size, "B")
    print("  植物:", len(plants), " 标签:", tag_total, " 大类:", len(group_order))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
